server:
  port: 3443

spring:
  application:
    name: Minecraft Panel
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  h2:
    console:
      enabled: false
  datasource:
    url: jdbc:h2:file:./data/minecraft-panel-db;AUTO_SERVER=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password: '${DB_PASSWORD:defaultSecretPassword}'

  web:
    resources:
      static-locations: classpath:/static/
  thymeleaf:
    cache: true
    enabled: true
    prefix: classpath:/templates/
    suffix: .html

  task:
    execution:
      pool:
        core-size: 4
        max-size: 8
        queue-capacity: 100
      thread-name-prefix: minecraft-async-
    scheduling:
      pool:
        size: 2
      thread-name-prefix: minecraft-scheduler-

logging:
  level:
    mc.server: INFO
    org.springframework: WARN
    org.hibernate: WARN
    nl.vv32.rcon: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never

minecraft:
  security:
    session-timeout: 5m

websocket:
  allowed-origins: "*"
  buffer-size: 8192
  max-sessions: 50