server:
  port: 3443
  servlet:
    context-path: /

spring:
  application:
    name: Minecraft Panel
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:./data/minecraft-panel-db
    driverClassName: org.h2.Driver
    username: sa
    password: ''

  security:
    user:
      name: ahror
      password: rorha4002
      roles: ADMIN

  web:
    resources:
      static-locations: classpath:/static/
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html

  task:
    execution:
      pool:
        core-size: 4
        max-size: 8
        queue-capacity: 100
      thread-name-prefix: minecraft-async-
    scheduling:
      pool:
        size: 2
      thread-name-prefix: minecraft-scheduler-

logging:
  level:
    mc.server: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web.socket: DEBUG
    nl.vv32.rcon: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

minecraft:
  security:
    session-timeout: 5m

websocket:
  allowed-origins: "*"
  buffer-size: 8192
  max-sessions: 50
